Fix opcode 17
```
>rs3cache.exe --dump achievements
```

```
thread 'main' panicked at 'not implemented: Achievement::deserialize cannot deserialize opcode 17 in id 1855:
 {
  "id": 1855
}', src\definitions\achievements.rs:242:28
```
After fix achievements.json is generated as expected.

Unsure if correct type is used for opcode 17 but it works.